# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='version',
            name='original_picture',
            field=models.ImageField(upload_to='static/original'),
        ),
        migrations.AlterField(
            model_name='version',
            name='watermark_picture',
            field=models.ImageField(upload_to='static/watermark'),
        ),
    ]
