# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181101_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
