# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181103_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='digital_picture',
            field=models.ImageField(default=' ', upload_to='static/digitalmark'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='favorite_number',
            field=models.IntegerField(default=0),
        ),
    ]
