# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20181104_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='original_picture',
            field=models.ImageField(upload_to='original'),
        ),
        migrations.AlterField(
            model_name='version',
            name='watermark_picture',
            field=models.ImageField(upload_to='watermark'),
        ),
    ]
