# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181104_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='download',
            old_name='version_id',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='picture_id',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pictureversion',
            old_name='picture_id',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='pictureversion',
            old_name='version_id',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='picture_id',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='picture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='version',
            name='digital_picture',
            field=models.ImageField(default=' ', upload_to='digitalmark'),
        ),
    ]
